# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a86657780b91fd84d769442338696a76891d9c7cb4838154a63dd5e92c0d8f9fc6f09a2c5a15965acb3a64d549e603dd04069e2bbfcdf1181cdde13f4a96dea

test:
  secret_key_base: 687aae909b43b055a021ba5fca2cb4a9ef954e5ebb3b0e787e5f5be37c91efb1075fea392b4b30a9d17bf86a285f01ca7109759d8a1c446f6669f9936be567dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
